### ISSUE TITLE
dot net 8 version issue with patch.ps1

### ISSUE THREAD

**Issue by cmhofmeister** [lextm/ancm-arm64#1]
Hey lextm,

I first want to say I really appreciate you posting this workaround.  I've been a developer for many years, but this is my first time dealing with web.  I'm trying to get through a 101 course on web apis and when step 1 of a 101 doesn't go well, it is very frustrating.  I can't believe that Microsoft, who just came out with the MAUI framework and knows that developers are using MacBooks doesn't see the value in this.

I have tried by best to follow the steps to run the provided scripts successfully on dot net 8, but having an issue.  Being a newbie to all of this, I apologize in advance if I'm doing something dumb.  If you have a few minutes to support this that would be wonderful, but I get how busy everyone is.

When I start running the script this is the first error message:
```
C:\>Powershell.exe -File patch.ps1 -msiFolder C:\msi\AttachedContainer
Patch files
Attempting stop...
Internet services successfully stopped
Copy-Item : Cannot find path 'C:\Program Files\IIS\Asp.Net Core Module\V2\18.0.24080\aspnetcorev2_outofprocess.dll'
because it does not exist.
```
Looking through the script I see that the version information (18.0.24080) seems to be obtained from aspnetcorev2.dll.

When I navigate to that base folder I see there is a version mismatch as I only have this folder:  
C:\Program Files\IIS\Asp.Net Core Module\V2\18.0.24081
Please note the 24081 vs 24080.

Aside from hacking the script, I was wondering if you have any idea or comments.

Thanks again.

**Comment by lextm** [comment]
En, pretty bad the convention was broken. I'll see how we might resolve this issue.

**Comment by lextm** [comment]
Switched to folder query to determine the version number.

This alternative way should apply to all .NET 7/8 versions, as only one child folder should be there (unless ASP.NET Core team makes another big change in the future).
