### ISSUE TITLE
dot net 8 hosting bundle does not seem to install all necessary files

### ISSUE THREAD

**Issue by cmhofmeister** [lextm/ancm-arm64#2]
Thanks much for taking the time.  I am getting further into the process thanks to your help with Issue #1.  I'm hoping you have time to provide feedback on another issue I am having.  The script seems to be expecting some dlls that are not there.

I installed the hosting bonding for dot net 8 from [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.4-windows-hosting-bundle-installer)

If I look at the files installed at C:\Program Files\IIS\Asp.Net Core Module it seems to be missing a file that the script is expecting:
-aspnetcorev2.dll

![image](https://github.com/lextm/ancm-arm64/assets/34583987/ad17540f-2271-4780-bbb6-116614d7ab40)

Likewise C:\Program Files\IIS\Asp.Net Core Module\V2\18.0.24081 is missing:
-aspnetcorev2_outofprocess.dll

![image](https://github.com/lextm/ancm-arm64/assets/34583987/6b376dcf-90c9-4d6b-8c9f-0026c18b4343)

The full script output:
```
C:\>Powershell.exe -File patch.ps1 -msiFolder C:\msi\AttachedContainer
Patching ASP.NET Core module version 18.0.24081
Patch files

Attempting stop...
Internet services successfully stopped
Copy-Item : Cannot find path 'C:\src\aspnetcorev2.dll' because it does not exist.
At C:\patch.ps1:57 char:5
+     Copy-Item .\src\aspnetcorev2.dll $main
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\src\aspnetcorev2.dll:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\src\aspnetcorev2_outofprocess.dll' because it does not exist.
At C:\patch.ps1:58 char:5
+     Copy-Item .\src\aspnetcorev2_outofprocess.dll $out
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\src\aspnetcorev2_outofprocess.dll:String) [Copy-Item], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand


Attempting start...
Internet services successfully started
Patched
.\sha1.ps1 : The term '.\sha1.ps1' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\patch.ps1:87 char:1
+ .\sha1.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\sha1.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by lextm** [comment]
That's exactly why the Readme file has also been updated earlier.

You will have to clone the entire repo locally and then run `patch.ps1`, as the necessary files are in the `src` folder.

**Comment by cmhofmeister** [comment]
Thank you so much for getting back to me.  I apologize for not seeing that the readme was updated.
